package pipeline

var macSmokeFiles = map[string][]string{
	"Testing/NativeUISmokeRunner.swift":                     {"core", "board"},
	"Testing/ConversationUISmokeRunner.swift":               {"conversation"},
	"Testing/MachineUISmokeRunner.swift":                    {"machine"},
	"Testing/SidebarNavigationUISmokeRunner.swift":          {"sidebar"},
	"Testing/TerminalUISmokeRunner.swift":                   {"terminal"},
	"Testing/IslandUISmokeRunner.swift":                     {"island"},
	"Testing/WorkspaceUISmokeRunner.swift":                  {"workspace"},
	"Testing/InboxUISmokeRunner.swift":                      {"inbox"},
	"UI/InboxView.swift":                                    {"inbox"},
	"UI/InboxFeed.swift":                                    {"inbox"},
	"Model/InboxActivity.swift":                             {"inbox"},
	"UI/BoardView.swift":                                    {"core", "board", "conversation", "workspace"},
	"UI/BoardLaneList.swift":                                {"core", "board"},
	"UI/BoardCardMergeDrop.swift":                           {"board"},
	"UI/BoardConversationOverlay.swift":                     {"core", "board", "conversation", "workspace"},
	"UI/ChatsView.swift":                                    {"core", "conversation", "sidebar", "inbox"},
	"UI/ConversationMarkdownView.swift":                     {"core", "board", "conversation"},
	"UI/SelectableMessageText.swift":                        {"core", "board", "conversation"},
	"UI/Attachments.swift":                                  {"core", "board", "conversation"},
	"UI/CaptureTask.swift":                                  {"core", "board", "conversation", "island"},
	"UI/DieterIslandView.swift":                             {"island"},
	"UI/DieterIslandWindow.swift":                           {"island"},
	"UI/MachinesView.swift":                                 {"core", "machine", "sidebar"},
	"UI/FilePaneSplit.swift":                                {"workspace"},
	"Features/Forms/EditCardSheet.swift":                    {"core", "board"},
	"Features/Forms/LabelForms.swift":                       {"core", "board"},
	"Features/Forms/BoardForms.swift":                       {"core", "board"},
	"Features/Forms/HarnessFields.swift":                    {"core", "board", "conversation"},
	"Features/Forms/NewConversationSheet.swift":             {"core", "board", "conversation"},
	"Features/Forms/ConversationWorkspacePickerSheet.swift": {"core", "board", "workspace"},
	"Model/BoardProjection.swift":                           {"core", "board"},
	"Model/DieterIslandPreferences.swift":                   {"island"},
	"Model/FileEditorSession.swift":                         {"core", "workspace"},
	"Model/ProjectChangesModel.swift":                       {"workspace"},
	"Model/WorkspaceGit.swift":                              {"workspace"},
	"Model/WorkspaceReview.swift":                           {"workspace"},
	"Model/ConversationRenderCache.swift":                   {"core", "board", "conversation"},
	"Model/ConversationPresentation.swift":                  {"core", "board", "conversation"},
	"Model/ConversationMarkdown.swift":                      {"core", "board", "conversation"},
	"Model/AttachmentLoader.swift":                          {"core", "board", "conversation", "island"},
}
var macSmokeComponents = map[string][]string{
	"Features/Conversation/": {"core", "board", "conversation", "workspace", "inbox"},
	"Features/Changes/":      {"workspace"},
	"Features/Files/":        {"core", "workspace"},
	"Features/Terminals/":    {"terminal"},
	"Features/Schedules/":    {"core", "board"},
	"Features/Search/":       {"core", "board", "sidebar"},
}
