#!/usr/bin/env python3
"""Generate the sole supported application contract constant for every client."""
from pathlib import Path
root = Path(__file__).resolve().parent.parent
version = (root / 'api/contract-version').read_text().strip()
assert version.isdecimal()
outputs = {
 'internal/protocol/version.go': f'// Code generated by scripts/generate-contract.py. DO NOT EDIT.\npackage protocol\n\nconst Version = "{version}"\n',
 'apps/mac/Sources/DieterAPI/DieterContract.swift': f'// Generated from api/contract-version.\npublic enum DieterContract {{ public static let version = "{version}" }}\n',
 'apps/android/app/src/main/java/com/dbpprt/dieter/data/DieterContract.kt': f'// Generated from api/contract-version.\npackage com.dbpprt.dieter.data\n\nconst val DIETER_API_VERSION = "{version}"\n',
}
for path, text in outputs.items():
    target = root / path
    if not target.exists() or target.read_text() != text:
        target.write_text(text)
