#!/usr/bin/env python3
"""Generate the sole supported application contract constant for every client."""
from pathlib import Path
root = Path(__file__).resolve().parent.parent
version = (root / 'api/contract-version').read_text().strip()
assert version.isdecimal()
outputs = {
 'native/macos-capture/DieterContract.swift': f'// Generated from api/contract-version.\nenum CaptureContract {{ static let version = {version} }}\n',
 'native/linux-capture/dieter-contract.h': f'// Generated from api/contract-version.\n#pragma once\n#define DIETER_CONTRACT_VERSION {version}\n',
 'internal/protocol/version.go': f'// Code generated by scripts/generate-contract.py. DO NOT EDIT.\npackage protocol\n\nconst Version = "{version}"\nconst Number = {version}\n',
 'apps/mac/Sources/DieterAPI/DieterContract.swift': f'// Generated from api/contract-version.\npublic enum DieterContract {{ public static let version = "{version}"; public static let number: UInt32 = {version} }}\n',
 'apps/android/app/src/main/java/com/dbpprt/dieter/data/DieterContract.kt': f'// Generated from api/contract-version.\npackage com.dbpprt.dieter.data\n\nconst val DIETER_API_VERSION = "{version}"\nconst val DIETER_PROTOCOL_VERSION = {version}\n',
}
for path, text in outputs.items():
    target = root / path
    if not target.exists() or target.read_text() != text:
        target.write_text(text)
